# Fos rest bundle configuration
fos_rest: 
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: false
  format_listener:
    rules: 
      - { path: ^/, priorities: ['json'], fallback_format: json }
  exception:
    enabled: true
    codes:
  view: 
    view_response_listener: 'force'
    formats: 
      json: true
    jsonp_handler:
            callback_param: false